#!/bin/bash

set -e

echo "[+] Creating .gitignore..."
cat > .gitignore << 'EOF'
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env*
!.env.example

# Mac files
.DS_Store

# VSCode files
.vscode/

# Build outputs
build/
dist/

# Python cache / venv
__pycache__/
*.pyc
*.pyo
*venv/
*.venv/
env/
venv/

# Uploads and Frames (if stored locally)
uploads/
frames/
EOF

echo "[+] Creating subdirectories: backend/ and frontend/"
mkdir -p backend frontend

echo "[+] Creating prompts.md..."
cat > prompts.md << 'EOF'
# LLM Interaction Log

## Phase 0: Setup & Environment
*(No LLM interactions needed for this phase)*

---
EOF

echo "[+] Initializing git repo and committing changes..."
git init
git add .gitignore prompts.md
git commit -m "Initial commit: Setup project structure, gitignore, prompts log"

echo "[+] Done. You can now optionally create a GitHub repo and push using:"
echo "   git remote add origin <REPO_URL>"
echo "   git push -u origin main"
